services:
  
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8502:8502"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: